#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
从 drama YAML 一键生成 scenes/ 并调用 scene_engine 渲染。

用法:
  python drama_builder.py dramas/nova_auckland_night.yaml
  python drama_builder.py dramas/nova_auckland_night.yaml --no-render
  python drama_builder.py dramas/nova_auckland_night.yaml --scenes-dir ./my_scenes
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "config"
DEFAULT_SCENES_DIR = ROOT / "scenes"
DEFAULT_OUTPUT_DIR = ROOT / "output_scenes"


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def slugify(text: str, max_len: int = 40) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    text = re.sub(r"[\s_]+", "_", text)
    return text[:max_len].strip("_") or "scene"


def resolve_path(base: Path, rel: str) -> Path:
    p = Path(rel)
    return p if p.is_absolute() else (base / p).resolve()


def copy_or_link(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        os.symlink(src, dst)
    except OSError:
        shutil.copy2(src, dst)


def write_script(beats: list[dict], script_path: Path) -> None:
    lines = ["# auto-generated by drama_builder.py", "# 格式: 开始秒-结束秒, \"字幕\", 位置, 缩放"]
    for beat in beats:
        start = int(beat["start"])
        end = int(beat["end"])
        subtitle = str(beat.get("subtitle", "")).replace('"', "'")
        position = beat.get("position", "center")
        scale = float(beat.get("scale", 0.5))
        lines.append(f'{start}-{end},"{subtitle}",{position},{scale}')
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_scenes(
    drama_path: Path,
    scenes_dir: Path,
    dolls: dict,
    backgrounds: dict,
    clean: bool = False,
) -> list[Path]:
    drama = load_yaml(drama_path)
    title = drama.get("title", drama_path.stem)
    doll_slug = drama["doll"]
    scene_defs = drama.get("scenes", [])

    if doll_slug not in dolls:
        raise SystemExit(f"未知娃娃 slug: {doll_slug!r}，请检查 config/dolls.yaml")
    doll = dolls[doll_slug]
    pose_paths = [resolve_path(ROOT, p) for p in doll.get("poses", [])]
    if not pose_paths:
        raise SystemExit(f"娃娃 {doll_slug} 没有配置 poses")

    missing_poses = [p for p in pose_paths if not p.exists()]
    if missing_poses:
        print("⚠️  以下姿势图不存在（请放到 assets/ 目录）:")
        for p in missing_poses:
            print(f"   - {p}")
        print("   仍会生成 script.txt，但 scene_engine 需要图片才能渲染。")

    if clean and scenes_dir.exists():
        shutil.rmtree(scenes_dir)
    scenes_dir.mkdir(parents=True, exist_ok=True)

    built: list[Path] = []
    print(f"\n🎬 剧集: {title}")
    print(f"   娃娃: {doll.get('name', doll_slug)} ({doll_slug})")
    print(f"   场景数: {len(scene_defs)}")

    for i, scene_def in enumerate(scene_defs, start=1):
        bg_slug = scene_def["background"]
        if bg_slug not in backgrounds:
            raise SystemExit(f"未知背景 slug: {bg_slug!r}，请检查 config/backgrounds.yaml")

        bg = backgrounds[bg_slug]
        bg_path = resolve_path(ROOT, bg["image"])
        scene_title = scene_def.get("title", bg.get("name", bg_slug))
        folder_name = f"{i:02d}_{slugify(scene_title)}"
        scene_path = scenes_dir / folder_name
        scene_path.mkdir(parents=True, exist_ok=True)

        beats = scene_def.get("beats", [])
        write_script(beats, scene_path / "script.txt")

        if bg_path.exists():
            ext = bg_path.suffix or ".jpg"
            copy_or_link(bg_path, scene_path / f"bg{ext}")
        else:
            print(f"   ⚠️  背景图不存在: {bg_path}")

        for j, pose_src in enumerate(pose_paths, start=1):
            if pose_src.exists():
                ext = pose_src.suffix or ".png"
                copy_or_link(pose_src, scene_path / f"model_{j:02d}{ext}")

        built.append(scene_path)
        print(f"   ✅ {folder_name}/ — {len(beats)} 句台词, 背景={bg_slug}")

    return built


def run_scene_engine(scenes_dir: Path, output_dir: Path) -> int:
    engine = ROOT / "scene_engine.py"
    if not engine.exists():
        print("❌ 找不到 scene_engine.py")
        return 1

    env = os.environ.copy()
    env["SCENES_DIR"] = str(scenes_dir)
    env["OUTPUT_DIR"] = str(output_dir)
    result = subprocess.run([sys.executable, str(engine)], cwd=str(ROOT), env=env)
    return result.returncode


def main() -> None:
    parser = argparse.ArgumentParser(description="从 drama YAML 生成场景并渲染")
    parser.add_argument("drama", type=Path, help="剧集 YAML，如 dramas/nova_auckland_night.yaml")
    parser.add_argument("--scenes-dir", type=Path, default=DEFAULT_SCENES_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--no-render", action="store_true", help="只生成 scenes/，不调用 scene_engine")
    parser.add_argument("--clean", action="store_true", help="生成前清空 scenes 目录")
    args = parser.parse_args()

    drama_path = args.drama if args.drama.is_absolute() else ROOT / args.drama
    if not drama_path.exists():
        raise SystemExit(f"找不到剧集文件: {drama_path}")

    dolls = load_yaml(CONFIG_DIR / "dolls.yaml")
    backgrounds = load_yaml(CONFIG_DIR / "backgrounds.yaml")

    print("=" * 55)
    print("  DollWorldwide — Drama Builder")
    print("=" * 55)

    build_scenes(drama_path, args.scenes_dir, dolls, backgrounds, clean=args.clean)

    if args.no_render:
        print(f"\n📁 场景已生成: {args.scenes_dir.resolve()}/")
        print("   手动渲染: python scene_engine.py")
        return

    print("\n" + "-" * 55)
    rc = run_scene_engine(args.scenes_dir, args.output_dir)
    sys.exit(rc)


if __name__ == "__main__":
    main()
