#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把本地 YAML 配置导出为 Supabase seed SQL。
后期部署：在 Supabase SQL Editor 先跑 schema.sql，再跑生成的 seed.sql。

用法:
  python yaml_to_supabase_seed.py
  python yaml_to_supabase_seed.py --drama dramas/nova_auckland_night.yaml
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "config"
DEFAULT_OUT = ROOT / "supabase" / "seed.sql"


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_array(tags: list) -> str:
    if not tags:
        return "array[]::text[]"
    items = ", ".join(sql_str(str(t)) for t in tags)
    return f"array[{items}]"


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    text = re.sub(r"[\s_]+", "_", text)
    return text.strip("_") or "drama"


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def emit_seed(drama_paths: list[Path], out_path: Path) -> None:
    dolls = load_yaml(CONFIG_DIR / "dolls.yaml")
    backgrounds = load_yaml(CONFIG_DIR / "backgrounds.yaml")

    lines = [
        "-- auto-generated by yaml_to_supabase_seed.py",
        "-- 在 supabase/schema.sql 之后运行",
        "",
    ]

    # dolls + poses
    for slug, doll in dolls.items():
        name = doll.get("name", slug)
        personality = doll.get("personality", "")
        default_scale = float(doll.get("default_scale", 0.5))
        lines.append(
            f"insert into dolls (slug, name, personality, default_scale) "
            f"values ({sql_str(slug)}, {sql_str(name)}, {sql_str(personality)}, {default_scale}) "
            f"on conflict (slug) do update set name = excluded.name, "
            f"personality = excluded.personality, default_scale = excluded.default_scale;"
        )
        for i, pose in enumerate(doll.get("poses", [])):
            # 本地路径 → 上云后替换为 Storage URL
            image_url = str(pose).replace("\\", "/")
            lines.append(
                f"insert into doll_poses (doll_id, sort_order, image_url) "
                f"select id, {i}, {sql_str(image_url)} from dolls where slug = {sql_str(slug)} "
                f"on conflict (doll_id, sort_order) do update set image_url = excluded.image_url;"
            )
        lines.append("")

    # backgrounds
    for slug, bg in backgrounds.items():
        name = bg.get("name", slug)
        tags = bg.get("tags", [])
        image_url = str(bg.get("image", "")).replace("\\", "/")
        lines.append(
            f"insert into backgrounds (slug, name, tags, image_url) "
            f"values ({sql_str(slug)}, {sql_str(name)}, {sql_array(tags)}, {sql_str(image_url)}) "
            f"on conflict (slug) do update set name = excluded.name, "
            f"tags = excluded.tags, image_url = excluded.image_url;"
        )
    lines.append("")

    # dramas
    for drama_path in drama_paths:
        drama = load_yaml(drama_path)
        title = drama.get("title", drama_path.stem)
        doll_slug = drama["doll"]

        lines.append(f"-- drama: {title}")
        lines.append(
            f"insert into dramas (id, title, doll_id, status) "
            f"select gen_random_uuid(), {sql_str(title)}, id, 'draft' from dolls "
            f"where slug = {sql_str(doll_slug)};"
        )
        lines.append(
            f"-- 用固定查询关联本剧（按 title 取最新一条）"
        )

        for i, scene_def in enumerate(drama.get("scenes", []), start=1):
            bg_slug = scene_def["background"]
            scene_title = scene_def.get("title", "")
            lines.append(
                f"insert into scenes (drama_id, sort_order, background_id, title) "
                f"select d.id, {i}, b.id, {sql_str(scene_title)} "
                f"from dramas d, backgrounds b "
                f"where d.title = {sql_str(title)} and b.slug = {sql_str(bg_slug)} "
                f"order by d.created_at desc limit 1 "
                f"on conflict (drama_id, sort_order) do update set "
                f"background_id = excluded.background_id, title = excluded.title;"
            )

            for j, beat in enumerate(scene_def.get("beats", []), start=1):
                subtitle = str(beat.get("subtitle", ""))
                position = beat.get("position", "center")
                scale = float(beat.get("scale", 0.5))
                pose_index = int(beat.get("pose_index", 0))
                lines.append(
                    f"insert into beats (scene_id, sort_order, start_sec, end_sec, subtitle, position, scale, pose_index) "
                    f"select s.id, {j}, {int(beat['start'])}, {int(beat['end'])}, "
                    f"{sql_str(subtitle)}, {sql_str(position)}, {scale}, {pose_index} "
                    f"from scenes s join dramas d on s.drama_id = d.id "
                    f"where d.title = {sql_str(title)} and s.sort_order = {i} "
                    f"on conflict (scene_id, sort_order) do update set "
                    f"start_sec = excluded.start_sec, end_sec = excluded.end_sec, "
                    f"subtitle = excluded.subtitle, position = excluded.position, "
                    f"scale = excluded.scale, pose_index = excluded.pose_index;"
                )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ 已生成 {out_path} ({len(lines)} 行)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--drama",
        type=Path,
        action="append",
        dest="dramas",
        help="剧集 YAML，可多次指定；默认扫描 dramas/*.yaml",
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    if args.dramas:
        drama_paths = [p if p.is_absolute() else ROOT / p for p in args.dramas]
    else:
        drama_paths = sorted((ROOT / "dramas").glob("*.yaml"))

    if not drama_paths:
        raise SystemExit("没有找到剧集 YAML")

    emit_seed(drama_paths, args.out if args.out.is_absolute() else ROOT / args.out)


if __name__ == "__main__":
    main()
